### ISSUE TITLE
Submitting a Search from the Home Page Results in Exception

### ISSUE THREAD

**Issue by dtotzke** [TwilioDevEd/employee-directory-csharp#8]
Steps to reproduce:

Run the application.
Click the "Go" Button.

See attached screenshot of exception details.

![twilioerror](https://user-images.githubusercontent.com/12560227/34737465-3c2a8992-f544-11e7-8d18-e727f26d1931.png)

**Comment by jazzchord** [comment]
Receiving the same error also.

**Comment by dprothero** [comment]
I was able to reproduce the issue. I'm looking into it now.

**Comment by dprothero** [comment]
Fixed!

https://github.com/TwilioDevEd/employee-directory-csharp/commit/30b6320bd11b94f5fc669a4335f6ac3c370931a9
